package net.avengingcondor.dyemod.item;

import net.avengingcondor.dyemod.DyeMod;
import net.avengingcondor.dyemod.block.ModBlocks;
import net.minecraft.core.registries.Registries;
import net.minecraft.network.chat.Component;
import net.minecraft.world.item.CreativeModeTab;
import net.minecraft.world.item.ItemStack;
import net.neoforged.bus.api.IEventBus;
import net.neoforged.neoforge.registries.DeferredRegister;

import java.util.function.Supplier;

public class ModCreativeModeTabs {
    public static final DeferredRegister<CreativeModeTab> CREATIVE_MODE_TAB = DeferredRegister.create(Registries.CREATIVE_MODE_TAB, DyeMod.MOD_ID);
   // private static Set<ItemStack> stainedGlassPanes = convertStainedGlass();

    public static final Supplier<CreativeModeTab> DYE_ITEMS_TAB = CREATIVE_MODE_TAB.register("more_dye_tab",
            () -> CreativeModeTab.builder().icon(() -> new ItemStack(ModBlocks.DYED_BLOCKS.get("wool").get("burgundy")/*ModBlocks.BURGUNDY_WOOL*/))
                    .title(Component.translatable("creativetab.condordyemod.dye_items"))
                    .displayItems((parameters, output) -> {
                        output.accept(ModItems.DYE_CRIMSON);
                        output.accept(ModItems.DYE_VERMILION);
                        output.accept(ModItems.DYE_AMBER);
                        output.accept(ModItems.DYE_CHARTREUSE);
                        output.accept(ModItems.DYE_OLIVE);
                        output.accept(ModItems.DYE_JADE);
                        output.accept(ModItems.DYE_LIGHT_GREEN);
                        output.accept(ModItems.DYE_TURQUOISE);
                        output.accept(ModItems.DYE_TEAL);
                        output.accept(ModItems.DYE_AZURE);
                        output.accept(ModItems.DYE_INDIGO);
                        output.accept(ModItems.DYE_MAUVE);
                        output.accept(ModItems.DYE_FUCHSIA);
                        output.accept(ModItems.DYE_BURGUNDY);
                        output.accept(ModItems.DYE_CORAL);
                        output.accept(ModItems.DYE_LIGHT_BROWN);
                        output.accept(ModBlocks.DYED_BLOCKS.get("wool").get("crimson"));
                        output.accept(ModBlocks.DYED_BLOCKS.get("wool").get("vermilion"));
                        output.accept(ModBlocks.DYED_BLOCKS.get("wool").get("amber"));
                        output.accept(ModBlocks.DYED_BLOCKS.get("wool").get("chartreuse"));
                        output.accept(ModBlocks.DYED_BLOCKS.get("wool").get("olive"));
                        output.accept(ModBlocks.DYED_BLOCKS.get("wool").get("jade"));
                        output.accept(ModBlocks.DYED_BLOCKS.get("wool").get("light_green"));
                        output.accept(ModBlocks.DYED_BLOCKS.get("wool").get("turquoise"));
                        output.accept(ModBlocks.DYED_BLOCKS.get("wool").get("teal"));
                        output.accept(ModBlocks.DYED_BLOCKS.get("wool").get("azure"));
                        output.accept(ModBlocks.DYED_BLOCKS.get("wool").get("indigo"));
                        output.accept(ModBlocks.DYED_BLOCKS.get("wool").get("mauve"));
                        output.accept(ModBlocks.DYED_BLOCKS.get("wool").get("fuchsia"));
                        output.accept(ModBlocks.DYED_BLOCKS.get("wool").get("burgundy"));
                        output.accept(ModBlocks.DYED_BLOCKS.get("wool").get("coral"));
                        output.accept(ModBlocks.DYED_BLOCKS.get("wool").get("light_brown"));
                        output.accept(ModBlocks.DYED_BLOCKS.get("carpet").get("crimson"));
                        output.accept(ModBlocks.DYED_BLOCKS.get("carpet").get("vermilion"));
                        output.accept(ModBlocks.DYED_BLOCKS.get("carpet").get("amber"));
                        output.accept(ModBlocks.DYED_BLOCKS.get("carpet").get("chartreuse"));
                        output.accept(ModBlocks.DYED_BLOCKS.get("carpet").get("olive"));
                        output.accept(ModBlocks.DYED_BLOCKS.get("carpet").get("jade"));
                        output.accept(ModBlocks.DYED_BLOCKS.get("carpet").get("light_green"));
                        output.accept(ModBlocks.DYED_BLOCKS.get("carpet").get("turquoise"));
                        output.accept(ModBlocks.DYED_BLOCKS.get("carpet").get("teal"));
                        output.accept(ModBlocks.DYED_BLOCKS.get("carpet").get("azure"));
                        output.accept(ModBlocks.DYED_BLOCKS.get("carpet").get("indigo"));
                        output.accept(ModBlocks.DYED_BLOCKS.get("carpet").get("mauve"));
                        output.accept(ModBlocks.DYED_BLOCKS.get("carpet").get("fuchsia"));
                        output.accept(ModBlocks.DYED_BLOCKS.get("carpet").get("burgundy"));
                        output.accept(ModBlocks.DYED_BLOCKS.get("carpet").get("coral"));
                        output.accept(ModBlocks.DYED_BLOCKS.get("carpet").get("light_brown"));
                        output.accept(ModBlocks.DYED_BLOCKS.get("terracotta").get("crimson"));
                        output.accept(ModBlocks.DYED_BLOCKS.get("terracotta").get("vermilion"));
                        output.accept(ModBlocks.DYED_BLOCKS.get("terracotta").get("amber"));
                        output.accept(ModBlocks.DYED_BLOCKS.get("terracotta").get("chartreuse"));
                        output.accept(ModBlocks.DYED_BLOCKS.get("terracotta").get("olive"));
                        output.accept(ModBlocks.DYED_BLOCKS.get("terracotta").get("jade"));
                        output.accept(ModBlocks.DYED_BLOCKS.get("terracotta").get("light_green"));
                        output.accept(ModBlocks.DYED_BLOCKS.get("terracotta").get("turquoise"));
                        output.accept(ModBlocks.DYED_BLOCKS.get("terracotta").get("teal"));
                        output.accept(ModBlocks.DYED_BLOCKS.get("terracotta").get("azure"));
                        output.accept(ModBlocks.DYED_BLOCKS.get("terracotta").get("indigo"));
                        output.accept(ModBlocks.DYED_BLOCKS.get("terracotta").get("mauve"));
                        output.accept(ModBlocks.DYED_BLOCKS.get("terracotta").get("fuchsia"));
                        output.accept(ModBlocks.DYED_BLOCKS.get("terracotta").get("burgundy"));
                        output.accept(ModBlocks.DYED_BLOCKS.get("terracotta").get("coral"));
                        output.accept(ModBlocks.DYED_BLOCKS.get("terracotta").get("light_brown"));
                        output.accept(ModBlocks.DYED_BLOCKS.get("glazed_terracotta").get("crimson"));
                        output.accept(ModBlocks.DYED_BLOCKS.get("glazed_terracotta").get("vermilion"));
                        output.accept(ModBlocks.DYED_BLOCKS.get("glazed_terracotta").get("amber"));
                        output.accept(ModBlocks.DYED_BLOCKS.get("glazed_terracotta").get("chartreuse"));
                        output.accept(ModBlocks.DYED_BLOCKS.get("glazed_terracotta").get("olive"));
                        output.accept(ModBlocks.DYED_BLOCKS.get("glazed_terracotta").get("jade"));
                        output.accept(ModBlocks.DYED_BLOCKS.get("glazed_terracotta").get("light_green"));
                        output.accept(ModBlocks.DYED_BLOCKS.get("glazed_terracotta").get("turquoise"));
                        output.accept(ModBlocks.DYED_BLOCKS.get("glazed_terracotta").get("teal"));
                        output.accept(ModBlocks.DYED_BLOCKS.get("glazed_terracotta").get("azure"));
                        output.accept(ModBlocks.DYED_BLOCKS.get("glazed_terracotta").get("indigo"));
                        output.accept(ModBlocks.DYED_BLOCKS.get("glazed_terracotta").get("mauve"));
                        output.accept(ModBlocks.DYED_BLOCKS.get("glazed_terracotta").get("fuchsia"));
                        output.accept(ModBlocks.DYED_BLOCKS.get("glazed_terracotta").get("burgundy"));
                        output.accept(ModBlocks.DYED_BLOCKS.get("glazed_terracotta").get("coral"));
                        output.accept(ModBlocks.DYED_BLOCKS.get("glazed_terracotta").get("light_brown"));
                        output.accept(ModBlocks.DYED_BLOCKS.get("stained_glass").get("crimson"));
                        output.accept(ModBlocks.DYED_BLOCKS.get("stained_glass").get("vermilion"));
                        output.accept(ModBlocks.DYED_BLOCKS.get("stained_glass").get("amber"));
                        output.accept(ModBlocks.DYED_BLOCKS.get("stained_glass").get("chartreuse"));
                        output.accept(ModBlocks.DYED_BLOCKS.get("stained_glass").get("olive"));
                        output.accept(ModBlocks.DYED_BLOCKS.get("stained_glass").get("jade"));
                        output.accept(ModBlocks.DYED_BLOCKS.get("stained_glass").get("light_green"));
                        output.accept(ModBlocks.DYED_BLOCKS.get("stained_glass").get("turquoise"));
                        output.accept(ModBlocks.DYED_BLOCKS.get("stained_glass").get("teal"));
                        output.accept(ModBlocks.DYED_BLOCKS.get("stained_glass").get("azure"));
                        output.accept(ModBlocks.DYED_BLOCKS.get("stained_glass").get("indigo"));
                        output.accept(ModBlocks.DYED_BLOCKS.get("stained_glass").get("mauve"));
                        output.accept(ModBlocks.DYED_BLOCKS.get("stained_glass").get("fuchsia"));
                        output.accept(ModBlocks.DYED_BLOCKS.get("stained_glass").get("burgundy"));
                        output.accept(ModBlocks.DYED_BLOCKS.get("stained_glass").get("coral"));
                        output.accept(ModBlocks.DYED_BLOCKS.get("stained_glass").get("light_brown"));
                        output.accept(ModBlocks.DYED_BLOCKS.get("stained_glass_panes").get("crimson"));
                        output.accept(ModBlocks.DYED_BLOCKS.get("stained_glass_panes").get("vermilion"));
                        output.accept(ModBlocks.DYED_BLOCKS.get("stained_glass_panes").get("amber"));
                        output.accept(ModBlocks.DYED_BLOCKS.get("stained_glass_panes").get("chartreuse"));
                        output.accept(ModBlocks.DYED_BLOCKS.get("stained_glass_panes").get("olive"));
                        output.accept(ModBlocks.DYED_BLOCKS.get("stained_glass_panes").get("jade"));
                        output.accept(ModBlocks.DYED_BLOCKS.get("stained_glass_panes").get("light_green"));
                        output.accept(ModBlocks.DYED_BLOCKS.get("stained_glass_panes").get("turquoise"));
                        output.accept(ModBlocks.DYED_BLOCKS.get("stained_glass_panes").get("teal"));
                        output.accept(ModBlocks.DYED_BLOCKS.get("stained_glass_panes").get("azure"));
                        output.accept(ModBlocks.DYED_BLOCKS.get("stained_glass_panes").get("indigo"));
                        output.accept(ModBlocks.DYED_BLOCKS.get("stained_glass_panes").get("mauve"));
                        output.accept(ModBlocks.DYED_BLOCKS.get("stained_glass_panes").get("fuchsia"));
                        output.accept(ModBlocks.DYED_BLOCKS.get("stained_glass_panes").get("burgundy"));
                        output.accept(ModBlocks.DYED_BLOCKS.get("stained_glass_panes").get("coral"));
                        output.accept(ModBlocks.DYED_BLOCKS.get("stained_glass_panes").get("light_brown"));
                        output.accept(ModBlocks.DYED_BLOCKS.get("concrete_powder").get("crimson"));
                        output.accept(ModBlocks.DYED_BLOCKS.get("concrete_powder").get("vermilion"));
                        output.accept(ModBlocks.DYED_BLOCKS.get("concrete_powder").get("amber"));
                        output.accept(ModBlocks.DYED_BLOCKS.get("concrete_powder").get("chartreuse"));
                        output.accept(ModBlocks.DYED_BLOCKS.get("concrete_powder").get("olive"));
                        output.accept(ModBlocks.DYED_BLOCKS.get("concrete_powder").get("jade"));
                        output.accept(ModBlocks.DYED_BLOCKS.get("concrete_powder").get("light_green"));
                        output.accept(ModBlocks.DYED_BLOCKS.get("concrete_powder").get("turquoise"));
                        output.accept(ModBlocks.DYED_BLOCKS.get("concrete_powder").get("teal"));
                        output.accept(ModBlocks.DYED_BLOCKS.get("concrete_powder").get("azure"));
                        output.accept(ModBlocks.DYED_BLOCKS.get("concrete_powder").get("indigo"));
                        output.accept(ModBlocks.DYED_BLOCKS.get("concrete_powder").get("mauve"));
                        output.accept(ModBlocks.DYED_BLOCKS.get("concrete_powder").get("fuchsia"));
                        output.accept(ModBlocks.DYED_BLOCKS.get("concrete_powder").get("burgundy"));
                        output.accept(ModBlocks.DYED_BLOCKS.get("concrete_powder").get("coral"));
                        output.accept(ModBlocks.DYED_BLOCKS.get("concrete_powder").get("light_brown"));
                        output.accept(ModBlocks.DYED_BLOCKS.get("concrete").get("crimson"));
                        output.accept(ModBlocks.DYED_BLOCKS.get("concrete").get("vermilion"));
                        output.accept(ModBlocks.DYED_BLOCKS.get("concrete").get("amber"));
                        output.accept(ModBlocks.DYED_BLOCKS.get("concrete").get("chartreuse"));
                        output.accept(ModBlocks.DYED_BLOCKS.get("concrete").get("olive"));
                        output.accept(ModBlocks.DYED_BLOCKS.get("concrete").get("jade"));
                        output.accept(ModBlocks.DYED_BLOCKS.get("concrete").get("light_green"));
                        output.accept(ModBlocks.DYED_BLOCKS.get("concrete").get("turquoise"));
                        output.accept(ModBlocks.DYED_BLOCKS.get("concrete").get("teal"));
                        output.accept(ModBlocks.DYED_BLOCKS.get("concrete").get("azure"));
                        output.accept(ModBlocks.DYED_BLOCKS.get("concrete").get("indigo"));
                        output.accept(ModBlocks.DYED_BLOCKS.get("concrete").get("mauve"));
                        output.accept(ModBlocks.DYED_BLOCKS.get("concrete").get("fuchsia"));
                        output.accept(ModBlocks.DYED_BLOCKS.get("concrete").get("burgundy"));
                        output.accept(ModBlocks.DYED_BLOCKS.get("concrete").get("coral"));
                        output.accept(ModBlocks.DYED_BLOCKS.get("concrete").get("light_brown"));
                        output.accept(ModBlocks.DYED_BLOCKS.get("candle").get("crimson"));
                        output.accept(ModBlocks.DYED_BLOCKS.get("candle").get("vermilion"));
                        output.accept(ModBlocks.DYED_BLOCKS.get("candle").get("amber"));
                        output.accept(ModBlocks.DYED_BLOCKS.get("candle").get("chartreuse"));
                        output.accept(ModBlocks.DYED_BLOCKS.get("candle").get("olive"));
                        output.accept(ModBlocks.DYED_BLOCKS.get("candle").get("jade"));
                        output.accept(ModBlocks.DYED_BLOCKS.get("candle").get("light_green"));
                        output.accept(ModBlocks.DYED_BLOCKS.get("candle").get("turquoise"));
                        output.accept(ModBlocks.DYED_BLOCKS.get("candle").get("teal"));
                        output.accept(ModBlocks.DYED_BLOCKS.get("candle").get("azure"));
                        output.accept(ModBlocks.DYED_BLOCKS.get("candle").get("indigo"));
                        output.accept(ModBlocks.DYED_BLOCKS.get("candle").get("mauve"));
                        output.accept(ModBlocks.DYED_BLOCKS.get("candle").get("fuchsia"));
                        output.accept(ModBlocks.DYED_BLOCKS.get("candle").get("burgundy"));
                        output.accept(ModBlocks.DYED_BLOCKS.get("candle").get("coral"));
                        output.accept(ModBlocks.DYED_BLOCKS.get("candle").get("light_brown"));
                        output.accept(ModBlocks.DYED_BLOCKS.get("shulker_box").get("crimson"));
                        output.accept(ModBlocks.DYED_BLOCKS.get("shulker_box").get("vermilion"));
                        output.accept(ModBlocks.DYED_BLOCKS.get("shulker_box").get("amber"));
                        output.accept(ModBlocks.DYED_BLOCKS.get("shulker_box").get("chartreuse"));
                        output.accept(ModBlocks.DYED_BLOCKS.get("shulker_box").get("olive"));
                        output.accept(ModBlocks.DYED_BLOCKS.get("shulker_box").get("jade"));
                        output.accept(ModBlocks.DYED_BLOCKS.get("shulker_box").get("light_green"));
                        output.accept(ModBlocks.DYED_BLOCKS.get("shulker_box").get("turquoise"));
                        output.accept(ModBlocks.DYED_BLOCKS.get("shulker_box").get("teal"));
                        output.accept(ModBlocks.DYED_BLOCKS.get("shulker_box").get("azure"));
                        output.accept(ModBlocks.DYED_BLOCKS.get("shulker_box").get("indigo"));
                        output.accept(ModBlocks.DYED_BLOCKS.get("shulker_box").get("mauve"));
                        output.accept(ModBlocks.DYED_BLOCKS.get("shulker_box").get("fuchsia"));
                        output.accept(ModBlocks.DYED_BLOCKS.get("shulker_box").get("burgundy"));
                        output.accept(ModBlocks.DYED_BLOCKS.get("shulker_box").get("coral"));
                        output.accept(ModBlocks.DYED_BLOCKS.get("shulker_box").get("light_brown"));
                    }).build());


    public static void register(IEventBus eventBus) {
        CREATIVE_MODE_TAB.register(eventBus);
    }

}
